name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: cd back-end/zero2hero && chmod +x gradlew
      - name: Build with Gradle
        run: cd back-end/zero2hero && ./gradlew test
